### model
model_name_or_path: /home/huangruijun/LLaMA-Factory/saves/qwen2-0.5b-instruct/full/quantity6stage_20k/checkpoint-300


### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
lora_rank: 16
lora_alpha: 16
lora_dropout: 0.05

### dataset
dataset: quantity6stage_meas
template: qwen
cutoff_len: 4098
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/qwen2-0.5b-instruct/lora/6stage_meas_2
logging_steps: 10
save_steps: 50
plot_loss: true
overwrite_output_dir: true
### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 16
learning_rate: 1.0e-4
num_train_epochs: 20.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 10